export const layout = {
    titlePanel : "Futebol",
    subTitlePanel: 'Copa do Mundo - Qatar 2022',
    gameTitle: 'BrasilXCroácia',
    gameSubtitle:['Casa', 'Fora'],
    gameDataTime:'09/12 06:00',
    imageGameURL: ['Assets/img/brazil-flag.png','Assets/img/croatia-flag.png'],
    winBetTitle: 'Aposte na vitória',
    winBetContent: 'Ganha na primeira metade', 
    winBetTitleSelectors: ['Casa','Empate','Fora'], 
    winBetContentSelectors: ['3.1','2.0','1.3'],
    gol1betTitle:"Outras apostas",
    gol1betCardTitle:'Gol no 1º tempo',
    gol1betTitleSelector:['Sim', 'Não'],
    gol1betContentSelector:['3.5','1.2'],
    gol2BetTitle: "1",
    gol2betCardTitle:'Gol no 2º tempo',
    gol2betTitleSelector:['Sim', 'Não'],
    gol2betContentSelector:['1.5','2.0'],
    winner1BetTitle: "Ganha na primeira metade",
    winner1BetTitleSelector:['Casa', 'Empate', 'Fora'],
    winner1BetContentSelector:['3.1','2.0','1.3'],
    winner2BetTitle: "Ganha na segunda metade",
    winner2BetTitleSelector:['Casa', 'Empate', 'Fora'],
    winner1BetContentSelector:['3.5','4.0','1.5'],
    valueBetTitle: "Finalizar Aposta",
    valueBetContentTitle:"Valor da Aposta",

}